# Generated by Django 4.2.1 on 2023-06-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcontent',
            name='webname',
            field=models.CharField(max_length=400),
        ),
    ]
